// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/liangchaofei/Desktop/demo/monorepo-site/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.2_@types+node@18.11.10_eslint@8.48.0_prettier@3.0.3_react-dom@18_f55zodvd3rokrsmjsxj2icxxn4/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/liangchaofei/Desktop/demo/monorepo-site/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/liangchaofei/Desktop/demo/monorepo-site/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.2_@types+node@18.11.10_eslint@8.48.0_prettier@3.0.3_react-dom@18_f55zodvd3rokrsmjsxj2icxxn4/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/liangchaofei/Desktop/demo/monorepo-site/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.2_@types+node@18.11.10_eslint@8.48.0_prettier@3.0.3_react-dom@18_f55zodvd3rokrsmjsxj2icxxn4/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
