// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liangchaofei/Desktop/demo/monorepo-site/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.2_@types+node@18.11.10_eslint@8.48.0_prettier@3.0.3_react-dom@18_f55zodvd3rokrsmjsxj2icxxn4/node_modules/dumi/theme-default/builtins/Previewer/index.js';
